### ISSUE TITLE
Ticketing System and Registration

### ISSUE THREAD

**Issue by chefscott** [djangocon/djangocon-us-docs#20]
- [ ] Select and setup ticketing system
- e.g., http://www.eventbrite.com/e/djangocon-us-2014-portland-or-tickets-11845045851
- [ ] Monitor ticket registrations

**Due date**: 06/05/2015

**Comment by jefftriplett** [comment]
Registration questions used by DjangoCon EU: https://www.dropbox.com/s/k3sz4tgbxlcdpzp/Screenshot%202015-05-09%2013.37.46.png?dl=0

**Comment by williln** [comment]
I like these, but I wonder if we need the student question.

We are able to collect dietary requirements and pass those along to the
venue, yes?

Can we link to the size chart for the t-shirts we'll be using? Sometimes
conferences order "juniors" shirts instead of "women's" shirts as the
fitted option, and those are sized very differently. (Also, can we not
order juniors t-shirts?)

Can we link to the accessibility page under the accommodations question, so
they'll know what we're already providing?

Replace "crèche" with "childcare." Since we're not sure we're offering it,
maybe we should ask, "if it were offered, would you take advantage of free
childcare?" And then also ask which days.

Move the meals question closer to the dietary requirements question.

**Comment by jefftriplett** [comment]
> We are able to collect dietary requirements and pass those along to the
venue, yes?

Yes. The venue claims to support omnivores, vegetarians, vegans, and gluten-free. 

> Can we link to the size chart for the t-shirts we'll be using? Sometimes
conferences order "juniors" shirts instead of "women's" shirts as the
fitted option, and those are sized very differently. (Also, can we not
order juniors t-shirts?)

The only consistent advice every conference organizer I've spoken with has given me is avoid t-shirts on your first-year planning. I think we are just going to do a tee-spring order so people can order them if they want. Plus I have a more unique swag idea.

> Can we link to the accessibility page under the accommodations question, so
they'll know what we're already providing?

We should be able to. I still don't have a contract from our ticket vendor but the systems appear to be flexible enough. I'll double check.

> Replace "crèche" with "childcare." Since we're not sure we're offering it,
maybe we should ask, "if it were offered, would you take advantage of free
childcare?" And then also ask which days.

I don't think we can afford "free" but I have contact information which is a good start. 

> Move the meals question closer to the dietary requirements question.

Noted.

**Comment by williln** [comment]
@jefftriplett Awesome! I can't wait to hear about your swag idea :) I fully support a tee-spring order in lieu of us ordering t-shirts. 
 
> The venue claims to support omnivores, vegetarians, vegans, and gluten-free.

That's great. I will add a Dietary section to the Accessibility page. 

> I don't think we can afford "free" [childcare] but I have contact information which is a good start.

Great. Suggested phrasing then, "Will you need childcare to attend this event?" With a note below that indicates that it would be for a fee.
